add configurable prometheus env label
livekit/livekit pull request #1421
Opened 2023-02-14 23:21 UTC by real-danm

This tags prometheus metrics with a configurable 'env' label. The default is either dev or prod.

2023-02-14 23:50 UTC, matkam requested changes

2023-02-14 23:50 UTC, matkam commented on pkg/config/config.go
> +	PrometheusEnv  string                   `yaml:"prometheus_env,omitempty"`
```suggestion
	Environment  string                   `yaml:"environment,omitempty"`
```

2023-02-14 23:50 UTC, matkam commented on cmd/server/main.go
> +	prometheus.Init(currentNode.Id, currentNode.Type, promEnv)
```suggestion
	prometheus.Init(currentNode.Id, currentNode.Type, conf.Environment)
```

2023-02-14 23:50 UTC, matkam commented on cmd/server/main.go
> +	prometheus.Init(currentNode.Id, currentNode.Type, promEnv)
to keep things in one place, put this in `config.go` `NewConfig(...)`:
```
if conf.Development {
  conf.Environment = "dev"
}
```

And I think its fine to leave the default as "" and not assume the environment name.

2023-02-14 23:50 UTC, matkam commented on config-sample.yaml
> +# prometheus_env: custom-label
```suggestion
# tag prometheus metrics with custom env label; defaults to empty string
# environment: custom-label
```

2023-02-15 04:10 UTC, boks1971 commented
> This tags prometheus metrics with a configurable 'env' label. The default is either dev or prod.

Maybe edit this to mention default is empty.

2023-02-15 04:10 UTC, boks1971 approved these changes

2023-02-15 21:08 UTC, matkam approved these changes

2023-02-15 21:41 UTC, merged